import '../globals.css'
import type { Metadata } from 'next'
import { Roboto as FontSans } from 'next/font/google'
import { cn } from '@/lib/utils'
import { Navbar } from '@/components/ui/navbar'
import { AuthProvider } from '@/lib/auth-context'
// import { Navbar } from '@/components/Navbar'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Movies App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={cn(
          'flex min-h-screen flex-col bg-foreground pb-4 font-sans text-background antialiased',
          fontSans.variable,
        )}
      >
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
